name: biotech_challenge
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cyvcf2=0.31.4
  - numpy>=2.3.5,<3.0a0
  - pandas>=2.0,<3
  - scipy>=1.11,<2
  - pip
  - pip:
      - pytest>=7.4,<9
      - python-dotenv>=1.0,<2
      - alphagenome
      - requests>=2.31,<3
      - -e .
